### ISSUE TITLE
most-subject/dist/most-subject.js not working in browser

### ISSUE THREAD

**Issue by dschalk** [TylorS/most-subject#16] opened 2016-05-26 20:05 UTC
I used most-subject successfully in the past. Then I switched to xstream for a while. Now I am trying to use most-subject version 4.02 but it won't load when I try it in Chrome. I am bundling with Webpack. I moved the whole npm package into bower_components because I need to get node_modules out of the way when I compile the server. I started out with just the /dist/most-subject.js file in bower_components and get identical results to the ones shown here. This is a screen shot of the top of of the Chrome console log:
![most-subject_top-of-console](https://cloud.githubusercontent.com/assets/2214003/15588128/72f8e5bc-235a-11e6-9a61-ae65bdeacfbe.png)
Here is line 9876 of the of the Webpack bundle:
![most-subject_9876](https://cloud.githubusercontent.com/assets/2214003/15588186/a3806b24-235a-11e6-91eb-df343f8434f4.png)
And here is line 9832
![most-subject_9842](https://cloud.githubusercontent.com/assets/2214003/15588219/c6ba3566-235a-11e6-8d44-98049a39bcc2.png)
The most relevant line seems to be line 7434. Here it is:
![most-subject_7434](https://cloud.githubusercontent.com/assets/2214003/15588243/e035ef58-235a-11e6-96f3-a4ca56713960.png)
This is a screen shot of my index.html file:
![index html](https://cloud.githubusercontent.com/assets/2214003/15588541/731d6eda-235c-11e6-8f52-591e90d0b363.png)

**Comment by TylorS** [comment] 2016-05-26 20:15
That's for all of this, I'll try to look into it very soon!

**Comment by dschalk** [comment] 2016-05-27 00:49
Thanks. By the way, I have a function something like this:
```javascript
function f(string) {
    var _this = this;
    this.id = string;
    this.stream = some stream;
    this g(x) {
        put x into _this.stream;
    }
}
var instance = new f;
```
I did this with `most-subject` and `xstream`, but I could not find a way to do it with most. If you, or anyone reading this, happens to know how to use most in this way, I would much appreciate your telling me. `most` uses `most-subject`, so I keep thinking the technology is somewhere inside of most.

Cheers!

**Comment by TylorS** [comment] 2016-05-27 03:22
So I think the issue is right in my face: https://github.com/TylorS/most-subject/blob/master/dist/most-subject.js#L4

The usage of most.defaultScheduler is not something that is accessible via the most builds currently.

I might backtrack and use browserify or something else and do separate builds of for node/browser

**Comment by dschalk** [comment] 2016-05-27 22:56
UPDATE: 
I don't know if this helps; but for what it is worth, I tried most version 18.8 and got this:
![most_18_5](https://cloud.githubusercontent.com/assets/2214003/15622981/afbcb3f6-243c-11e6-8f27-eb8b9c80aef0.png)

**Comment by TylorS** [comment] 2016-05-29 20:28
Hey @dschalk As soon as  https://github.com/mostjs/prelude/pull/8 gets merged, I have a rewrite in TypeScript with a new build system that should fix this issue. Hopefully by the end of the night :)

**Comment by dschalk** [comment] 2016-05-30 22:03
Thanks. I am eager to switch back to most-subject. 

The new version does not crash the browser or give any error messages. The new version's API is different from what I remember so I am experimenting. As I recall, subject() returned an object with a "stream" attribute, but that isn't the case now.

 I am experimenting with the return value of mostSubject.subject in my Chrome console log. When I run s =  mostSubject.subject(), I get an object with many methods, including "next" and "observe". So far, I have gotten no results and no error messages. Obviously I am missing something.  

So, naturally, I clicked the link to https://tylors.github.io/most-subject/doc, but the page is not there. Chrome displays the 404  "File not found" page.

**Comment by TylorS** [comment] 2016-05-30 23:04
The APi has channged with v4 - thanks for pointing out that there are issues with the docs as well. I'l ltry to get that fixed as well.

In the mean time, the API is as follows
```diff
- const {observer, stream} = subject()
+ const stream = subject()

stream.observe(x => console.log(x)

- observer.next(1)
+ stream.next(1)

- observer.error(new Error('error'))
+ stream.error(new Error('error'))

- observer.complete()
+ stream.complete()

```

**Comment by TylorS** [comment] 2016-05-30 23:14
http://codepen.io/TylorS/pen/rLNgrZ?editors=0010

**Comment by dschalk** [comment] 2016-05-30 23:22
Thanks again. The example is just what I needed.

**Comment by TylorS** [comment] 2016-05-30 23:25
:+1: I'll close this then. Feel free to reopen if its needed

**Closed by TylorS** 2016-05-30 23:25 UTC

**Comment by dschalk** [comment] 2016-05-31 00:28
I think the issue is resolved, so I am not trying to reopen it. I am writing this to say that I don't think "then" is working in the example you gave me. When I run the code shown below, the output remains the same: three results, no result repeated. 
```javascript
stream.observe(x => console.log(x))
  .then(x => console.log(x))
  .then(x => console.log(x))
  .then(x => console.log(x))
  .then(x => console.log(x))
  .then(x => console.log(x))
  .catch(e => console.error(e))

stream.next(1)
stream.next(2)
stream.next(3)
stream.complete('complete') 
```
Browser console:
1
2
3

**Comment by TylorS** [comment] 2016-05-31 01:37
Strange indeed, I'm not getting the same behavior here :/

![image](https://cloud.githubusercontent.com/assets/6282473/15660785/b2d57112-26ae-11e6-82ae-dbbc13b81d36.png)

**Comment by dschalk** [comment] 2016-05-31 02:12
Does it print each number twice? It only prints the numbers once for me. I don't need next right now, but I thought I should tell you what I got when I ran the code. I expected it to log a number once when the promise resolved and again on the call to "next".

I made the transition from xstream back to most-subject. My app is running flawlessly (as far as I can tell, anyway) at http://schalk.net:3055.

**Comment by TylorS** [comment] 2016-05-31 02:35
They print just once for me as well. `then()` is only called on `complete()` which is the same behavior the most has itself.

I'm curious, are you using most-subject for the ability to imperatively call `complete()`?

**Comment by dschalk** [comment] 2016-05-31 07:43
No. Here is the story:
My app runs online at http://schalk.net:3055. The repo is at https://github.com/dschalk/JS-monads-stable. In the repo at /client/monad.js there is this:
```javascript
var MonadStream = function MonadStream(g) {
  var _this = this;
  this.id = g;
  this.stream = mostSubject.subject()
  this.ret = function (a) {
    _this.stream.next(a);
    console.log('in ' + _this.id + ' emmitting ' + a);
    return _this;
  };
};

var mM$1 = new MonadStream('mM$1');
```
And one of its uses is (in /client/main line 626) is this
```javascript
  const mM$1Action$ = mM$1.stream.observe(v => {
      console.log('In mM$1Action$. v is: ', v)
      O.mMindex2.bnd(inc, mMindex2);
      O.mMallRolls.bnd(spliceAdd, O.mMindex2.x, v, mMallRolls);
      mMcurrentRoll.ret(v);
      document.getElementById('0').innerHTML = (O.mMallRolls.x[O.mMindex2.x])[0]; 
      document.getElementById('1').innerHTML = (O.mMallRolls.x[O.mMindex2.x])[1]; 
      document.getElementById('2').innerHTML = (O.mMallRolls.x[O.mMindex2.x])[2]; 
      document.getElementById('3').innerHTML = (O.mMallRolls.x[O.mMindex2.x])[3]; 
      cleanup(7)
  })
```
I tried to define MonadStream using only most and was unable to come up with an algorithm that worked. I think I could define MonadStream with RxJS and Bacon, and I have successfully done so with xstream and most-subject.  Now that the state of my monads is in the mutable global object "O", the slickest solution might be to use ordinary monads defined by Monad (in /client/monads.js at line 49) and the ordinary "ret()" method, which mutates "O" and automatically runs every expression observing it. There's a spreadsheed-like calculator in the online app at http://schalk.net:3055, demonstrating that this works. 

I keep thinking that there must be a way to define MonadStream with most. That's why I asked if anybody knows how to do it in the off-topic comment above. The tools don't seem to be in the most API, so I think I would need to study and understand the most code. That would be a project for me.

I am awe-struck by Motorcycle.js, My monad experiments thrive in Motorcycle. I am using most-subject for streaming mostly because I feel so comfortable in the environment that you and your collaborators have created.
